/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testapp_NativeAlpr */

#ifndef _Included_com_example_testapp_NativeAlpr
#define _Included_com_example_testapp_NativeAlpr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testapp_NativeAlpr
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_openalpr_NativeAlpr_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
